import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>
      </main>

      <h1 className="title">
        Read{" "}
        <Link href="/test/first-test">
          <a>this page!</a>
        </Link>
      </h1>
    </div>
  );
}
